Code quality - Code sniffer and phpstan
chrom/m2snippets pull request #12
Opened 2020-11-05 10:59 UTC by alex311982

2020-11-05 22:08 UTC, chrom requested changes

2020-11-05 22:08 UTC, chrom commented on app/code/Andrew/Quality_tools/README.md
> +После этого можно инспектировать код используя магентовские рулы. Например:
Как на счет установки правил в PHPStorm dev/tests/static/framework/Magento/ruleset.xml?

2020-11-05 22:24 UTC, chrom requested changes

2020-11-05 22:24 UTC, chrom commented on app/code/Andrew/Quality_tools/README.md
> +```
Если будут проблемы с обнаружением правил для magento 2 нужно добавить конфигурацию
vendor/bin/phpcs --config-set installed_paths ../../magento/magento-coding-standard/

2020-11-05 22:28 UTC, chrom requested changes

2020-11-05 22:28 UTC, chrom commented on app/code/Andrew/Quality_tools/README.md
> +# Code Sniffer
Объеденить в один документ по качеству кода.

2020-11-09 16:16 UTC, alex311982 commented on app/code/Andrew/Quality_tools/README.md
> +# Code Sniffer
Выполнено. Общий мердж-риквест https://github.com/chrom/m2snippets/pull/13.

2020-11-09 16:17 UTC, alex311982 commented on app/code/Andrew/Quality_tools/README.md
> +После этого можно инспектировать код используя магентовские рулы. Например:
Выполнено. Общий мердж https://github.com/chrom/m2snippets/pull/13.

2020-11-09 16:17 UTC, alex311982 commented on app/code/Andrew/Quality_tools/README.md
> +```
Выполнено. Общий мердж https://github.com/chrom/m2snippets/pull/13.

2020-11-12 14:37 UTC, closed without merging