Mess detector and pre-commit hook phpStan
chrom/m2snippets pull request #13
Opened 2020-11-05 14:01 UTC by SaftaArtem

2020-11-05 22:29 UTC, chrom requested changes

2020-11-05 22:46 UTC, chrom requested changes

2020-11-05 22:46 UTC, chrom commented on app/code/Andrew/Quality_tools/MessDetector.md
> +В magento 2 присутствует в дев зависимостях. Настроить очень легко.
Объеденить в один документ по качеству [кода](https://github.com/chrom/m2snippets/pull/12#discussion_r518408573).

2020-11-05 22:46 UTC, chrom commented on app/code/Andrew/Quality_tools/pre-commit
> +phpcs="/var/www/magento.loc/vendor/bin/phpcs --report=code --colors --report-width=80 --standard=PSR2 --ignore=${ignore}"
Установить правильные относительные пути.

2020-11-05 22:46 UTC, chrom commented on app/code/Andrew/Quality_tools/pre-commit
> +#!/usr/bin/env bash
Добавить отдельным разделом в документ по качеству [кода](https://github.com/chrom/m2snippets/pull/12#discussion_r518408573).

2020-11-10 08:32 UTC, SaftaArtem commented on app/code/Andrew/MagentoInstall/ArtemSafta/install-magento2.sh
> +#!/bin/bash
Ok, это касается другого pr

2020-11-10 08:32 UTC, SaftaArtem commented on app/code/Andrew/Quality_tools/MessDetector.md
> +PHP Mess Detector (обнаружитель беспорядков), будучи установленным, обрабатывает ваш код утилитой PHP_Depend и использует полученные метрики для составления собственных отчётов.
поменял

2020-11-10 08:33 UTC, SaftaArtem commented on app/code/Andrew/Quality_tools/MessDetector.md
> +В magento 2 присутствует в дев зависимостях. Настроить очень легко.
сделано

2020-11-10 08:33 UTC, SaftaArtem commented on app/code/Andrew/Quality_tools/pre-commit
> +phpcs="/var/www/magento.loc/vendor/bin/phpcs --report=code --colors --report-width=80 --standard=PSR2 --ignore=${ignore}"
установил

2020-11-10 08:33 UTC, SaftaArtem commented on app/code/Andrew/Quality_tools/pre-commit
> +#!/usr/bin/env bash
добавил

2020-11-12 14:43 UTC, alex311982 commented on app/code/Andrew/MagentoInstall/ArtemSafta/install-magento2.sh
> +#!/bin/bash
Этот файл переделан

2020-11-13 11:58 UTC, merged