Install Magento Overview
chrom/m2snippets pull request #6
Opened 2020-10-30 08:09 UTC by SaftaArtem

Mage Tv Lessons

2020-11-05 23:07 UTC, chrom requested changes

2020-11-09 16:08 UTC, SaftaArtem commented on app/code/Andrew/MagentoInstall/ArtemSafta/README.MD
> +	3 склонировать magento 2 с репозитооряи на гихабе
fixed

2020-11-10 08:35 UTC, SaftaArtem commented on app/code/Andrew/MagentoInstall/ArtemSafta/install-magento2.sh
> +./bin/magento setup:install \
добавил

2020-11-11 13:09 UTC, SaftaArtem commented on app/code/Andrew/MagentoInstall/ArtemSafta/README.MD
> +	Выполнить установку через браузер
fixed

2020-11-30 15:45 UTC, merged